import os
import io
import base64
import numpy as np
from PIL import Image
from flask import Flask, render_template, jsonify, request
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
app = Flask(__name__)
# Constants
SIZE = 256
PIXEL_RESOLUTION = 23.5 # LISS-3 resolution in meters
PIXEL_AREA_SQ_M = PIXEL_RESOLUTION * PIXEL_RESOLUTION # 552.25 sq meters
# Spectral signatures for automated K-Means label mapping
SIGNATURE_TEMPLATES = {
    'water':      np.array([ 60,  50,  20,   5]),
    'vegetation': np.array([ 90,  45, 220,  80]),
    'builtup':    np.array([140, 150, 160, 170]),
    'sandy':      np.array([170, 200, 215, 245]),
    'other':      np.array([105, 120, 130, 145])
}
CLASS_INFO = {
    'water':      {'name': 'Water Body',        'color': [0, 119, 182]},      # Premium Blue
    'vegetation': {'name': 'Vegetation Area',   'color': [46, 117, 89]},     # Forest Green
    'builtup':    {'name': 'Building Area',     'color': [230, 57, 70]},     # Built-up Coral Red
    'sandy':      {'name': 'Sandy Area',        'color': [233, 196, 106]},   # Soft Sand Yellow
    'other':      {'name': 'Other Area',        'color': [108, 117, 125]}    # Neutral Grey
}
CLASS_KEYS = list(CLASS_INFO.keys())
def load_bands_and_ground_truth(region, year):
    """Loads the 4-band spectral array and the ground truth map."""
    data_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static', 'data')
    
    bands_file = os.path.join(data_dir, f"{region}_{year}_bands.npy")
    gt_file = os.path.join(data_dir, f"{region}_{year}_gt.png")
    
    if not os.path.exists(bands_file) or not os.path.exists(gt_file):
        # Auto-generate if missing
        import generate_mock_data
        generate_mock_data.main()
        
    bands = np.load(bands_file)
    gt_img = Image.open(gt_file)
    return bands, gt_img
def get_simulated_training_data(region, year, sample_fraction=0.03):
    """
    Simulates training ROI selection in QGIS.
    Samples pixels from the known ground truth map, adds noise,
    and returns features (bands) and labels.
    """
    bands, gt_img = load_bands_and_ground_truth(region, year)
    gt_arr = np.array(gt_img)
    
    # Map colors back to class keys
    color_to_key = {}
    # Ground truth colors generated by generate_mock_data.py
    gt_colors = {
        'water': [0, 0, 255],
        'vegetation': [0, 200, 0],
        'builtup': [200, 50, 50],
        'sandy': [240, 220, 130],
        'other': [150, 150, 150]
    }
    
    flat_gt = np.zeros((SIZE, SIZE), dtype=int)
    for idx, (key, color) in enumerate(gt_colors.items()):
        mask = np.all(gt_arr == color, axis=-1)
        flat_gt[mask] = idx
        
    # Sample pixels
    x_train = []
    y_train = []
    
    for idx, key in enumerate(CLASS_KEYS):
        mask = (flat_gt == idx)
        coords = np.argwhere(mask)
        if len(coords) == 0:
            continue
        # Randomly choose sample size
        n_samples = int(max(20, len(coords) * sample_fraction))
        indices = np.random.choice(len(coords), n_samples, replace=False)
        sampled_coords = coords[indices]
        
        for r, c in sampled_coords:
            x_train.append(bands[r, c])
            y_train.append(idx)
            
    return np.array(x_train), np.array(y_train)
def classify_kmeans(bands, k_clusters=5):
    """Performs K-Means unsupervised classification and maps clusters to logical classes."""
    X = bands.reshape(-1, 4)
    kmeans = KMeans(n_clusters=k_clusters, random_state=42, n_init='auto')
    labels = kmeans.fit_predict(X)
    centers = kmeans.cluster_centers_
    
    # Map each cluster center to the closest class template
    cluster_mapping = {}
    for cluster_idx in range(k_clusters):
        center = centers[cluster_idx]
        min_dist = float('inf')
        best_class = 'other'
        for class_name, template in SIGNATURE_TEMPLATES.items():
            dist = np.linalg.norm(center - template)
            if dist < min_dist:
                min_dist = dist
                best_class = class_name
        cluster_mapping[cluster_idx] = CLASS_KEYS.index(best_class)
        
    # Re-map labels
    mapped_labels = np.vectorize(cluster_mapping.get)(labels)
    return mapped_labels.reshape(SIZE, SIZE)
def classify_supervised(bands, X_train, y_train, algo='random_forest', n_estimators=50, C=1.0):
    """Performs Supervised classification (Random Forest or SVM)."""
    X = bands.reshape(-1, 4)
    
    if algo == 'random_forest':
        clf = RandomForestClassifier(n_estimators=n_estimators, random_state=42)
    elif algo == 'svm':
        # Scale features for SVM
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_scaled = scaler.transform(X)
        clf = SVC(C=C, kernel='rbf', probability=True, random_state=42)
        clf.fit(X_train_scaled, y_train)
        labels = clf.predict(X_scaled)
        return labels.reshape(SIZE, SIZE)
    else:
        raise ValueError("Unknown supervised algorithm")
        
    clf.fit(X_train, y_train)
    labels = clf.predict(X)
    return labels.reshape(SIZE, SIZE)
def get_class_metrics(classified_map):
    """Calculates area statistics (hectares, percentage) for each class."""
    total_pixels = SIZE * SIZE
    unique, counts = np.unique(classified_map, return_counts=True)
    count_dict = dict(zip(unique, counts))
    
    metrics = []
    for idx, key in enumerate(CLASS_KEYS):
        count = count_dict.get(idx, 0)
        percentage = (count / total_pixels) * 100
        area_ha = (count * PIXEL_AREA_SQ_M) / 10000.0 # 1 hectare = 10,000 sq meters
        area_sq_km = (count * PIXEL_AREA_SQ_M) / 1000000.0
        
        metrics.append({
            'id': key,
            'name': CLASS_INFO[key]['name'],
            'color': CLASS_INFO[key]['color'],
            'pixels': int(count),
            'percentage': round(percentage, 2),
            'area_ha': round(area_ha, 2),
            'area_sq_km': round(area_sq_km, 3)
        })
    return metrics
def create_color_map_base64(classified_map):
    """Converts classified map matrix to PNG base64 string for display."""
    color_img = np.zeros((SIZE, SIZE, 3), dtype=np.uint8)
    for idx, key in enumerate(CLASS_KEYS):
        color_img[classified_map == idx] = CLASS_INFO[key]['color']
        
    img = Image.fromarray(color_img)
    buffered = io.BytesIO()
    img.save(buffered, format="PNG")
    img_str = base64.b64encode(buffered.getvalue()).decode('utf-8')
    return img_str
@app.route('/')
def home():
    return render_template('index.html')
@app.route('/api/classify', methods=['POST'])
def classify():
    data = request.json or {}
    region = data.get('region', 'jodhpur')
    year = data.get('year', '2024')
    algorithm = data.get('algorithm', 'random_forest')
    
    # Algorithm parameters
    k_clusters = int(data.get('k_clusters', 5))
    n_estimators = int(data.get('n_estimators', 50))
    svm_c = float(data.get('svm_c', 1.0))
    
    try:
        bands, _ = load_bands_and_ground_truth(region, year)
        
        if algorithm == 'kmeans':
            classified_map = classify_kmeans(bands, k_clusters)
        else: # random_forest or svm
            x_train, y_train = get_simulated_training_data(region, year)
            classified_map = classify_supervised(bands, x_train, y_train, algorithm, n_estimators, svm_c)
            
        metrics = get_class_metrics(classified_map)
        img_base64 = create_color_map_base64(classified_map)
        
        return jsonify({
            'success': True,
            'region': region,
            'year': year,
            'algorithm': algorithm,
            'metrics': metrics,
            'image': f"data:image/png;base64,{img_base64}"
        })
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500
@app.route('/api/change_detection', methods=['POST'])
def change_detection():
    data = request.json or {}
    region = data.get('region', 'jodhpur')
    algorithm = data.get('algorithm', 'random_forest')
    
    # Parameters
    k_clusters = int(data.get('k_clusters', 5))
    n_estimators = int(data.get('n_estimators', 50))
    svm_c = float(data.get('svm_c', 1.0))
    
    try:
        bands_2024, _ = load_bands_and_ground_truth(region, '2024')
        bands_2025, _ = load_bands_and_ground_truth(region, '2025')
        
        if algorithm == 'kmeans':
            map_2024 = classify_kmeans(bands_2024, k_clusters)
            map_2025 = classify_kmeans(bands_2025, k_clusters)
        else:
            # Train and classify 2024
            x_tr_24, y_tr_24 = get_simulated_training_data(region, '2024')
            map_2024 = classify_supervised(bands_2024, x_tr_24, y_tr_24, algorithm, n_estimators, svm_c)
            # Train and classify 2025
            x_tr_25, y_tr_25 = get_simulated_training_data(region, '2025')
            map_2025 = classify_supervised(bands_2025, x_tr_25, y_tr_25, algorithm, n_estimators, svm_c)
            
        metrics_2024 = get_class_metrics(map_2024)
        metrics_2025 = get_class_metrics(map_2025)
        
        # Calculate transition matrix (change grid)
        # We compute how many pixels shifted from class A to class B
        transition_matrix = np.zeros((len(CLASS_KEYS), len(CLASS_KEYS)), dtype=int)
        for r in range(SIZE):
            for c in range(SIZE):
                c_24 = map_2024[r, c]
                c_25 = map_2025[r, c]
                transition_matrix[c_24, c_25] += 1
                
        # Format transition matrix for response
        transition_data = []
        for r_idx, from_key in enumerate(CLASS_KEYS):
            row_data = {}
            for c_idx, to_key in enumerate(CLASS_KEYS):
                pixel_count = int(transition_matrix[r_idx, c_idx])
                area_ha = (pixel_count * PIXEL_AREA_SQ_M) / 10000.0
                row_data[to_key] = {
                    'pixels': pixel_count,
                    'area_ha': round(area_ha, 2)
                }
            transition_data.append({
                'from_id': from_key,
                'from_name': CLASS_INFO[from_key]['name'],
                'transitions': row_data
            })
            
        # Calculate net changes
        net_changes = []
        for m24, m25 in zip(metrics_2024, metrics_2025):
            diff_ha = m25['area_ha'] - m24['area_ha']
            diff_pct = m25['percentage'] - m24['percentage']
            net_changes.append({
                'id': m24['id'],
                'name': m24['name'],
                'color': m24['color'],
                'area_2024': m24['area_ha'],
                'area_2025': m25['area_ha'],
                'diff_ha': round(diff_ha, 2),
                'diff_pct': round(diff_pct, 2)
            })
            
        img_24_b64 = create_color_map_base64(map_2024)
        img_25_b64 = create_color_map_base64(map_2025)
        
        return jsonify({
            'success': True,
            'region': region,
            'algorithm': algorithm,
            'metrics_2024': metrics_2024,
            'metrics_2025': metrics_2025,
            'image_2024': f"data:image/png;base64,{img_24_b64}",
            'image_2025': f"data:image/png;base64,{img_25_b64}",
            'net_changes': net_changes,
            'transition_matrix': transition_data
        })
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500
if __name__ == '__main__':
    # Ensure data is generated before startup
    data_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static', 'data')
    if not os.path.exists(os.path.join(data_dir, "jodhpur_2024_bands.npy")):
        print("Generating mock remote sensing data...")
        import generate_mock_data
        generate_mock_data.main()
        
     app.run(host="0.0.0.0", port=5000)
